name: pinned
description: "A travel project. Built with Flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Utility
  intl: ^0.19.0
  equatable: ^2.0.5
  meta: ^1.15.0
  collection: ^1.18.0
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  device_info_plus: ^11.1.1
  share_plus: ^10.1.2
  mask_text_input_formatter: ^2.9.0
  stream_transform: ^2.1.0

  # For Third Party
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.4
  newrelic_mobile: ^1.1.5

  # For Architecture
  injectable: ^2.5.0
  get_it: ^8.0.1
  riverpod: ^2.6.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  melos: ^6.2.0

  # For Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # For Routing
  go_router: ^14.6.2

  # For UIs
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.5
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  chewie: ^1.8.5
  video_player: 2.9.2
  pdf: ^3.11.1
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  flutter_widget_from_html: ^0.15.3
  flutter_inappwebview: ^6.1.5
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.1.3

  # For Networking
  dio: ^5.7.0
  ua_client_hints: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_flavorizr: ^2.2.3

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/